oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accesskeyId: LTAI4GEqZhGmKgXxD2TtYQRQ
  accesskeySecret: A2jh1jgc35qfRxYQfhZvbLqMOQyIZr
Alipay:
  serverUrl: https://openapi.alipaydev.com/gateway.do
  APP_ID: 2021000116658997
  APP_PRIVATE_KEY: 
  FORMAT: json
  CHARSET: UTF-8
  ALIPAY_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAi82bO5joBEUD+iSJg+kH4QX3u3yqA8BnXNt6MJJ+WoqvcEWIJaCbg23nMId0W4gsupySDz3OEmqJBWey2cNpF0eRXUsYEI99jP9prFQHZQgzmB+Mf3UXt/DqFD0s/qPmCdCAoasBBk0IJojmN9kzbm9fcPByilVaGpBv7eY+7hIpkdJClgpQiVMEMgkIiKqIyjl82HWLL9iZzhsn+5bOR2E8o6Vc0g6x1YMSJqyShkRBASF7w10eHjFAeXi3UeeLKwO+F+ulmN7SnOPEs5tLVtcHCfNHjqr7J+AP4K0LTKKynh5cCkHZjDVCoTaN2fVuIDDvuqsyqLSug3Log8Q60QIDAQAB
  SIGN_TYPE: RSA2
