server:
  port: 7500
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JamboHH/steam-config.git # 配置git仓库的地址
          search-paths: steam-config
          default-label: main
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:80/eureka
  instance:
    prefer-ip-address: true
    hostName: ${spring.cloud.client.ip-address}
    instance-id: http://${spring.cloud.client.ip-address}:${server.port}
